### ISSUE TITLE
No coverage when using a asp.net core TestServer and integration testing

### ISSUE THREAD

**Issue by ghandmann** [lucaslorentz/minicover#103]
Hi There!
We are really looking forward for this project and got up and running quite fast.

But we now discovered some odd behavior: When combining minicover with ASP.net Core [integration testing based on the TestServer](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#introduction-to-integration-tests), we get zero coverage in the API controllers. I have created a minimal reproducer:

https://github.com/ghandmann/minicover-reproducer

The "funny" thing here is: When i instrument the DLLs and then start the WebAPI-Project with `dotnet run` and hit the ndpoints minicover is able to collect coverage. Only when the (sucessfull) integration tests hit the same endpoints, we don't see any coverage.

Do you have any idea, whats going on here? Something wrong with our setup? Or a bug in minicover?

**Comment by majkinetor** [comment]
> The "funny" thing here is: When i instrument the DLLs and then start the WebAPI-Project with dotnet run and hit the ndpoints minicover is able to collect coverage. 

@ghandmann, It looks I am trying to achieve precisely that without much success (described on [SO](https://stackoverflow.com/questions/63870883/code-coverage-of-asp-net-core-app-with-test-done-in-pester)). Would you help me by confirming this: you run the app normally, no unit tests are involved, and hit any endpoint using whatever method, which makes it generate coverage ?

I did the following but got 0 everywhere:

```
minicover instrument --sources **/*.cs
dotnet run ...
[ do bunch of Invoke-RestMethod hitting various REST endpoints]
[ kill the service ]
minicover uninstrument
minicover htmlreport
```
```
