### ISSUE TITLE
Multiple assemblies or source files

### ISSUE THREAD

**Issue by MCFHTAGENTS** [lucaslorentz/minicover#110]
Please can you advise what pattern matching for paths you are  using. I need to pass in DirectoryA OR Directory B as a path for sources and it is not clear how I can do this. I can't use **/*.cs as there are other directories in that folder that I don't want to include.
Thanks
Mark

**Comment by lucaslorentz** [comment]
You can pass multiple values in all pattern match options.
```
--sources "folderA/**/*.cs" --sources "folderB/**/*.cs"
```
Same applies to assemblies, tests, exclude-aasemblies, exclude-tests, exclude-sources.

**Comment by lucaslorentz** [comment]
I'm using Microsoft library for globbing Microsoft.Extensions.FileSystemGlobbing
AFAIK they don't support OR inside the same pattern.

**Comment by MCFHTAGENTS** [comment]
Thanks - I have that working now (please can you spell out in the documentation :) as there are a number of patterns it could have been). I am following the instructions here:
https://github.com/llatinov/SampleDotNetCore2RestStub/blob/master/codeCoverage.sh
but with Visual Studio 2019 I am running the instrumentation command against my DLL in it's local directory. MS Studio I think then copies that DLL and PDB into another directory for testing. Do I need to replicate that in a batch file and just copy the DLL and PDB or are there other files I need to copy? At the moment I am not seeing any coverage by my tests which is not right.

**Comment by lucaslorentz** [comment]
I think it is very likely that visual studio rebuilds and overrides the instrumented assemblies when it runs tests.

Ideally you should run tests via command line with a --no-build option, so it run tests without rebuilding the assemblies.

Also, make sure you instrument the assemblies in your test project bin folder. Those are the ones used during test.

I think the assembly pattern "**/*.dll" should work, as it will probably find assemblies in your test folder as well.

**Comment by MCFHTAGENTS** [comment]
Thanks - sorted. Changing that wildcard did it. One thing I did notice is I get the following exception:
Unhandled exception. System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(Disposable`1 stream, String fileName, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at MiniCover.Instrumentation.AssemblyInstrumenter.InstrumentAssembly(InstrumentationContext context, FileInfo assemblyFile) in /home/vsts/work/1/s/src/MiniCover/Instrumentation/AssemblyInstrumenter.cs:line 50
   at MiniCover.Instrumentation.Instrumenter.VisitAssemblyGroup(InstrumentationContext context, InstrumentationResult result, IEnumerable`1 groupFiles) in /home/vsts/work/1/s/src/MiniCover/Instrumentation/Instrumenter.cs:line 78
   at MiniCover.Instrumentation.Instrumenter.Execute(InstrumentationContext context) in /home/vsts/work/1/s/src/MiniCover/Instrumentation/Instrumenter.cs:line 51
   at MiniCover.Commands.InstrumentCommand.Execute() in /home/vsts/work/1/s/src/MiniCover/CommandLine/Commands/InstrumentCommand.cs:line 98
   at MiniCover.CommandLine.BaseCommand.<AddTo>b__8_1() in /home/vsts/work/1/s/src/MiniCover/CommandLine/BaseCommand.cs:line 34
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args) in /home/vsts/work/1/s/src/MiniCover/Program.cs:line 57
probably as there is a C++ DLL in that path. It would be a kindness if you caught it, generated a warning in the log, and skipped the DLL.

**Comment by lucaslorentz** [comment]
Are you using the latest minicover version 3.0.2?

**Comment by MCFHTAGENTS** [comment]
Yes...
Thanks
Mark

**Comment by lucaslorentz** [comment]
@MCFHTAGENTS 
I checked the code again, and we only instrument assemblies that have a .pdb file with same name.
I believe that's not the case for C++ DLLs.

Probably you have a message right before the exception like: 'Checking assembly file {assembly}'.

Could you please let me know which assembly is failing to load?

If you don't see that message, you're probably using an older version of MInicover.

**Comment by MCFHTAGENTS** [comment]
Hi I will check that when back in front of my PC but building C++ files definitely creates PDBs!

https://devblogs.microsoft.com/cppblog/whats-inside-a-pdb-file/

This is how you should be testing for assemblies I think:

https://stackoverflow.com/questions/1366503/best-way-to-check-if-a-dll-file-is-a-clr-assembly-in-c-sharp

Thanks
Mark

Sent from my iPhone

On 26 Nov 2019, at 08:59, Lucas Lorentz <notifications@github.com> wrote:

﻿

@MCFHTAGENTS<https://github.com/MCFHTAGENTS>
I checked the code again, and we only instrument assemblies that have a .pdb file with same name.
I believe that's not the case for C++ DLLs.

Probably you have a message right before the exception like: 'Checking assembly file {assembly}'.

Could you please let me know which assembly is failing to load?

If you don't see that message, you're probably using an older version of MInicover.

**Comment by MCFHTAGENTS** [comment]
Hi,
I can confirm it is 'my' C++ DLL that causes the exception. That there is a PDB file of the same name as the DLL and if I look through the code on GitHub for Mono.Cecil.PE I think you rather than they should probably handle the exception :) as they explicitly throw it.

The offending line is:

`AssemblyDefinition.ReadAssembly(assemblyFile.FullName, new ReaderParameters { ReadSymbols = true, AssemblyResolver = resolver }))`

in
`minicover/src/MiniCover/Instrumentation/AssemblyInstrumenter.cs`

I can work round for now by adding the DLL to my exclude list.

Thanks
Mark

**Comment by lucaslorentz** [comment]
Exception handled: https://github.com/lucaslorentz/minicover/commit/5fe614aee029ccf70b8ead824a0466dbf9472657

Could you please try version 3.0.3?

**Comment by MCFHTAGENTS** [comment]
Hi there - that looks fixed. Thank you for your help
Mark
