### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MCFHTAGENTS** [lucaslorentz/minicover#111]
Hi there
i am generally finding this tool quite slow. I have a relatively small website and the total process of running the reset, build, instrument, xmlreport and conversion is taking approx. 12 hours.

I suspect, but haven't yet proven that my anti-virus system will be the culprit but I note that I have of the order of 1.2 million files in the content-hits directory and generally I have seen poor performance across Windows when there are large number of files in a directory.

Generally, it would seem to me better if the content-hits were stored in a database. Either a relational one or a file based one. This is a suggestion for such an enhancement.

Thanks
Mark

**Comment by lucaslorentz** [comment]
Interesting, can you please try to reference your test sources as well? Using --tests parameter.

Let me know if that changes the performance

**Comment by lucaslorentz** [comment]
I will try to fix that in the next days, it is a known issue but I expected it to be slightly better now.

**Comment by MCFHTAGENTS** [comment]
Hi - I am using the --tests parameter :(. Looking at the code a few observations:
 - GetFiles is Slower that EnumerateFiles when running the Reset command
[See here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/816039eb-23db-455f-8186-b3a4a8989043/what-is-the-fastest-way-to-enumerate-large-number-of-files-in-a-folder?forum=netfxbcl)
[and here](https://stackoverflow.com/questions/197162/ntfs-performance-and-large-volumes-of-files-and-directories/291292)
I will switch off the AV when my current run has completed and I can try it again
To give some data executing 176 tests took 3.2 hours.
Am sure putting the data in a database would help!

Will update once I have more info.

Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
A further useful link:
https://serverfault.com/questions/95444/storing-a-million-images-in-the-filesystem/95447#95447

**Comment by MCFHTAGENTS** [comment]
ok - I think I can see what is happening here - my machines are all using file level backup solutions. We are shovelling 1m files across it and I can't restrict it by location so each of those files is moving in multiple places. Hmmmmm

**Comment by lucaslorentz** [comment]
I recently switched to an approach that creates too many small files.
I will switch back to  less but bigger files.

**Comment by lucaslorentz** [comment]
I think this will improve your case: https://github.com/lucaslorentz/minicover/commit/927a4b299872989d5e73b38e297a8ef7bb78fcd0

I will package a version now.

**Comment by lucaslorentz** [comment]
Please, try again with version 3.0.4. It will be published soon.

**Comment by MCFHTAGENTS** [comment]
Thank you - working through now. Will up date in due course
Thanks 
Mark

**Comment by MCFHTAGENTS** [comment]
Thank you - confimed fixed. - down to mere minutes
