### ISSUE TITLE
3.05 - never completes

### ISSUE THREAD

**Issue by MCFHTAGENTS** [lucaslorentz/minicover#114]
Hi there,
I have just installed your 3.05 release and it seems to get stuck on my main DLL at 'Instrumenting' - any thoughts on how I can detect what is happening? I would hazard a guess it is in an infinite loop!

It does not do this on all DLLs and I am trying to look here to see what code has changed that could trigger it. I am not yet running on 3.1 as had big issues with the 3.0 build and am busy completing my unit tests!

Thanks
Mark

**Comment by lucaslorentz** [comment]
I'm working on a fix for that. I unlisted the package from nuget.org because of that issue. It will be fixed in a few days.

**Comment by lucaslorentz** [comment]
@MCFHTAGENTS Could you please try v3.0.6-beta1?
It worked much better on my projects. I will create version 3.0.6 after your feedback.

https://www.nuget.org/packages/MiniCover/3.0.6-beta1

**Comment by MCFHTAGENTS** [comment]
No good I am afraid the same thing is happening - any views on how I can easily debug etc?

**Comment by lucaslorentz** [comment]
@MCFHTAGENTS 
Could you please try again with 3.0.6-beta2?

I added unit tests covering more graph infinite recursions.

**Comment by MCFHTAGENTS** [comment]
Lucas
Thanks it looks like that ran through to completion and created the relevant output
Thank you for your help
Mark

Sent from my iPhone

On 10 Dec 2019, at 22:30, Lucas Lorentz <notifications@github.com> wrote:

﻿

@MCFHTAGENTS<https://github.com/MCFHTAGENTS>
Could you please try again with 3.0.6-beta2?

I added unit tests covering more graph infinite recursions.

**Comment by lucaslorentz** [comment]
Fixed In version 3.0.6
