### ISSUE TITLE
Configure return code if threshold is not reached

### ISSUE THREAD

**Issue by VladislavAntonyuk** [lucaslorentz/minicover#121]
currently if coverage threshold is not reached, the tool exits with code 1. it breaks the continue tasks running. 
I would like to set a boolean flag like --ignoreThreshold, which if it is true, the program will exit with ExitCode=0;

**Comment by lucaslorentz** [comment]
Can you set threshold to 0? Or do you want to use threshold to color your report output?

**Comment by VladislavAntonyuk** [comment]
I want to use threshold to color report output

**Comment by lucaslorentz** [comment]
@VladislavAntonyuk 
Thanks, implemented as `--no-fail` and released in version 3.1.0.
