### ISSUE TITLE
Add more test result formats

### ISSUE THREAD

**Issue by VladislavAntonyuk** [lucaslorentz/minicover#124]
Please add support for "plist" and "JUnit XML" test result formats

**Comment by lucaslorentz** [comment]
Could you please share a link with documentation about those formats, and or samples?

They're usually quick to implement, the hardest sometimes is to find good examples and the right spec about the format.

**Comment by lucaslorentz** [comment]
Those are not very common formats on .NET ecosystem.
Closed due to the lack of documentation or samples.
