### ISSUE TITLE
Sporatic generation of hits

### ISSUE THREAD

**Issue by olafurbergs** [lucaslorentz/minicover#127]
Hey,

I am trying to use minicover to instrument a running aspnet core webapi running inside of a container and get coverage from integration tests which stimulate the webapi through http to get api contract vs code test coverage.

Been at this for days now and getting mixed results.  I have narrowed it down to that sometimes it seems that the hitsservice is able to write hits which results in coverage reports with hits and sometimes an empty hitfile or sometimes no file which results in no coverage, seems random or a so called race condition.

Do you have any Idea why I am getting either a normal report with hits or an empty report from different runs?

Is there anything specific about how it handles the exit of the app/test?
From what I understand is that it writes out the hits at program exit.
Is there anything I can do to guarentee the generation of the hits file?

here is the entrypoint.sh and Dockerfile ... any help would be appreciated.

```bash
  #!/bin/bash
  set -x
  export PATH=/root/.dotnet/tools/:$PATH
  pid=0
  term_handler() {
    pid=$(pgrep -f "dotnet exec")
    ppid=$(pgrep -f "dotnet run")
    if [ $pid -ne 0 ]; then
      kill $pid 
      wait $ppid
      ls -ltr ./coverage/hits > ./coverage-reports/coverage-hits-WebApi.txt 
      minicover report --coverage-file=./coverage/coverage.json > ./coverage-reports/coverage-WebApi.txt
      minicover htmlreport --coverage-file=./coverage/coverage.json --output=./coverage-reports/html-WebApi
      minicover coberturareport --coverage-file=./coverage/coverage.json --output=./coverage-reports/cobertura-WebApi.xml
      minicover opencoverreport --coverage-file=./coverage/coverage.json --output=./coverage-reports/opencover-WebApi.xml
    fi 
    exit 0; 
  } 
  trap "killall tail; term_handler" SIGTERM
  minicover instrument --sources=**/*.cs --coverage-file=./coverage/coverage.json --hits-directory=./coverage/hits
  dotnet run --server.urls http://0.0.0.0:80 --project Project --no-build --no-restore --no-launch-profile --verbosity diag &
  while true
  do
    tail -f /dev/null & wait $!
  done
```

```dockerfile
  FROM my-private-registry/my-dotnet-sdk:2.1
  COPY WebApi /src/WebApi
  WORKDIR /src/WebApi
  RUN dotnet restore && dotnet build
  WORKDIR /src
  COPY entrypoint.sh /entrypoint.sh
  RUN mkdir -p coverage/hits coverage-reports && chmod u+x /entrypoint.sh
  ENTRYPOINT ["bash", "-c", "/entrypoint.sh"]
```

**Comment by olafurbergs** [comment]
Hey,
Thanks for replying.
The webapi is being run in a docker compose scenario, with --abort-on-container-exit set so that when the tests have been run the whole scenario is torn down.  From what I understand it's sending SIGTERM to the container.  I have also tested this with running only the webapi container and stopping it with docker stop {container} which ends in the same results.

**Comment by olafurbergs** [comment]
Hey,

I tried removing the static file handling of the HitService and just write a hits file for every dispose.

This gives me consistent behaviour and consistent output.

```csharp
using System;
using System.IO;

namespace MiniCover.HitServices
{
    public static class HitService
    {
        public static MethodContext EnterMethod(
            string hitsPath,
            string assemblyName,
            string className,
            string methodName)
        {
            return new MethodContext(hitsPath, assemblyName, className, methodName);
        }

        public class MethodContext : IDisposable
        {
            private static object _hitContextLock = new object();
            private readonly string _hitsPath;
            private readonly HitContext _hitContext;

            public MethodContext(
                string hitsPath,
                string assemblyName,
                string className,
                string methodName)
            {
                _hitsPath = hitsPath;
                _hitContext = new HitContext(assemblyName, className, methodName);
            }

            public void Hit(int id)
            {
                _hitContext.RecordHit(id);
            }

            public void Dispose()
            {
                var fileStream = CreateOutputFile(_hitsPath);
                lock (fileStream)
                {
                    _hitContext.Serialize(fileStream);
                    fileStream.Flush();
                    fileStream.Close();
                }
           }

            private static FileStream CreateOutputFile(string hitsPath)
            {
                Directory.CreateDirectory(hitsPath);
                var filePath = Path.Combine(hitsPath, $"{Guid.NewGuid()}.hits");
                return File.Open(filePath, FileMode.CreateNew);
            }
        }
    }
}
```

**Comment by lucaslorentz** [comment]
That makes sense, most of the problems are related to buffering and aggregating hits before writing to disk.
We buffer the output to not degrade application performance too much.
We need a better and more stable approach than what we have today.

**Comment by lucaslorentz** [comment]
Is this issue still happening?
Can anyone please provide a reproducible repository?
