### ISSUE TITLE
Error when use with .net core 3.1

### ISSUE THREAD

**Issue by rafaeldeveloper-lin** [lucaslorentz/minicover#128]
When I try to use the minicover 3.1 with .net core 3.1 I always have the error

**error NU1202: Package MiniCover 3.1.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package MiniCover 3.1.0 supports:**

and

**error NU1212: Invalid project-package combination for MiniCover 3.1.0. DotnetToolReference project style can only contain references of the DotnetTool type** 

I have all this packages in my test.csproj

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.1.9" />
  </ItemGroup>
  
  <ItemGroup>  
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" /> 
  </ItemGroup>

**Comment by lucaslorentz** [comment]
.NET Core 2.1 introduced a better way to install tools:
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

Now you don't need to reference minicover in a csproj anymore.
You can install it globally with:
```
dotnet tool install --global minicover
```

Or locally with:
```
dotnet tool install minicover
```

**Comment by rafaeldeveloper-lin** [comment]
Thanks man, It's working.
