### ISSUE TITLE
Performance of report

### ISSUE THREAD

**Issue by exyi** [lucaslorentz/minicover#13]
Hi, I have tried to use minicover in my project and the `dotnet minicover report` was really slow, so I launched a profiler and:

![image](https://user-images.githubusercontent.com/7894687/35827304-61ed3470-0ab3-11e8-966f-15e7c5454a69.png)

The usage of Array.Contains in the BaseReport seems to completelly kill performance - https://github.com/lucaslorentz/minicover/blob/master/src/MiniCover/Reports/BaseReport.cs#L38. I think that using `HashSet` will resolve the issue instantly.

Anyway, thank you for making this project, it actually works which is awesome ;)

**Comment by lucaslorentz** [comment]
Thanks for pinpointing the bottleneck.

I agree that a hashset would improve performance a lot.

I will create a PR later.

Good to know it is working properly 😄

**Comment by lucaslorentz** [comment]
@exyi. I've merged PRs with optimization.

Feel free to re-open this issue if you think we need to optimize it further.
