### ISSUE TITLE
Minicover 3.1.0 is not output the cover

### ISSUE THREAD

**Issue by rafaeldeveloper-lin** [lucaslorentz/minicover#132]
HI,

I'm trying to use minicover but all the time the cover don't put the result in window like the photo that I attached above, test is running fine

![image](https://user-images.githubusercontent.com/73120455/97737708-257c2980-1abc-11eb-9225-78cfa3908aaf.png)

My code

![image](https://user-images.githubusercontent.com/73120455/97737587-f9f93f00-1abb-11eb-9f6b-446239ca8d11.png)

can you help me?

**Comment by lucaslorentz** [comment]
Can you please describe the folders you have in your project?

Try removing "workdir ../". And add a . before the assemblies and sources, so they become a relative path. Try modifying the the pattern as well because it is probably not finding any files.

Like:
minicover instrument --assemblies ./tests/**/*.dll

Have you tried as well with only?
minicover instrument

**Comment by rafaeldeveloper-lin** [comment]
My folder is something like this

-- PathPrincipal
  ------src
  ------tests
    --------units


The minicover is generating the folders(coverate-hits, coverate-html) and file coverage.json in root folder

 but continue to show  
![image](https://user-images.githubusercontent.com/73120455/97980946-4f7d6680-1db0-11eb-8d27-497baa5ba60a.png)

**Comment by lucaslorentz** [comment]
Did you try to run from PathPrincipal folder without workdir parameter? Like the readme suggests:
https://github.com/lucaslorentz/minicover#build-script-example

Not clear to me if you tried without workdir already.

Based on your folder structure (src+tests folder), it should work by just following the readme script.

Can you create a git repo with a reproducible scenario? I would be able to help you more with it.

**Comment by rafaeldeveloper-lin** [comment]
I tried run from PathPrincipal and this work
Thank you soo much
