### ISSUE TITLE
.NET 5 support?

### ISSUE THREAD

**Issue by ffMathy** [lucaslorentz/minicover#133]
Does this library support .NET 5 yet?

**Comment by lucaslorentz** [comment]
Added net5 as a nuget package target as well.
That way you don't need older runtimes to install and run it.

**Comment by lucaslorentz** [comment]
Released on 3.3.0.
https://www.nuget.org/packages/MiniCover/3.3.0

**Comment by ffMathy** [comment]
Great! <3
