### ISSUE TITLE
--threshold no longer supported for opencoverreport

### ISSUE THREAD

**Issue by HarrySnipe** [lucaslorentz/minicover#148]
Is there a reason this is no longer supported?

**Comment by HarrySnipe** [comment]
I noticed in closed issues this had already been raised and explained, sorry for this.

**Comment by lucaslorentz** [comment]
Hey, no problem.

I believe the threshold is more tied to the tool that is displaying/visualizing the coverage information, and not to the coverage file itself.

Therefore I removed the option from reports that don't use it in the output.
 
If you want your build to fail based on a threshold, you can additionally generate the console or htmlreport as they still support threshold.
