### ISSUE TITLE
As a user I want to have a monospaced font for source code

### ISSUE THREAD

**Issue by thisisthekap** [lucaslorentz/minicover#15]
See e.g. http://hivelogic.com/articles/top-10-programming-fonts/

**Comment by lucaslorentz** [comment]
Nice catch. Source code looks a bit weird indeed 😄 

What do you think about using browser default "monospace" font?
I prefer to not prioritize monospaced fonts based on my preferences, and users still can customize the browser default monospace font.

**Comment by thisisthekap** [comment]
@lucaslorentz Thank you very much for your fast response and your effort!

Even though I would prefer a fixed configured nice looking font (google font or something like that), the PR delivers what I was asking for. To my point of view, it is not neccessary to make the used font configurable.

**Comment by lucaslorentz** [comment]
I understand your preference, maybe we will get there in the future.

But as you said, this very simple change already delivers what you asked. So, why not making it super simple, at least for now 😄 

With the PR I merged you can select your preferred monospaced font on Google Chrome font preferences:

<kbd>
<img width="412" alt="screen shot 2018-02-06 at 6 36 28 pm" src="https://user-images.githubusercontent.com/2268284/35882885-b60ea3fe-0b6c-11e8-81f5-5e6672a3f59a.png">
</kbd>

Thanks

**Comment by thisisthekap** [comment]
When will the change be available in a nuget package?

**Comment by lucaslorentz** [comment]
It is available already.
 
MiniCover 2.0.0-ci-20180206203706

Just point your tool to the new version: `<DotNetCliToolReference Include="MiniCover" Version="2.0.0-ci-20180206203706" />`

**Comment by lucaslorentz** [comment]
For now we're using pre-release CI packages.

But soon we will need to release final versions and improve release process.
