### ISSUE TITLE
Minicover 3.6.1 does not generate coverage after implementing GeneratedRegex from .NET7.

### ISSUE THREAD

**Issue by Asaelsilva** [lucaslorentz/minicover#168]
Hello,

Recently, I upgraded a project from .NET6 to .NET7. With the new approach of using regex, I implemented and started using GeneratedRegex in the project. However, I noticed that when using GeneratedRegex, Minicover stopped generating test coverage.

I am using Minicover version 3.6.1.

![Minicover](https://github.com/lucaslorentz/minicover/assets/41707970/c34a6042-54ba-407f-a344-ba73686ecf2b)

I can't identify the relationship between these two elements (GeneratedRegex and Minicover) causing this issue. However, I would like to continue using GeneratedRegex and, at the same time, ensure that Minicover continues to display test coverage.

Is there any explanation for this behavior and a possible solution to this issue?

Thank you.

**Comment by gustavojuneo** [comment]
Same issue here.
