### ISSUE TITLE
htmlreport fails if directory path doesn't already exist

### ISSUE THREAD

**Issue by corrydiehl** [lucaslorentz/minicover#22]
When executing:
`dotnet minicover htmlreport --workdir ../ --threshold 90`
I get a DirectoryNotfoundException.

Seems maybe a "CreateDirectory()" in the "WriteFooter()" method before attempting to write out the html file can fix this?

**Comment by lucaslorentz** [comment]
Thanks. Did exactly what you said.

It should be fixed in version: MiniCover 2.0.0-ci-20180212211119

**Comment by corrydiehl** [comment]
Thanks much for the update @lucaslorentz! I would have done a PR but I didn't know how you felt about contributions. I really appreciate you creating this project, I'm actively pursuing it as a solution for a few projects I'm working with. Interested to know if you have any roadmap or future plans for Minicover.
