### ISSUE TITLE
Can't build the solution using VS

### ISSUE THREAD

**Issue by HigorCesar** [lucaslorentz/minicover#23]
I tried to build the solution with VS 2017 and got the error:
![minicover-fails-to-build-vs2017](https://user-images.githubusercontent.com/434889/36149764-4d1c80f0-10c1-11e8-85d6-81bf084cb9b1.png)

To solve it I had to add the MiniCover.Tests to the solution, is there a reason to not add it?

**Comment by lucaslorentz** [comment]
Not at all. I was using command line too much and didn't remember to update the solution.

I will fix it later, or accept a PR if you have some time. 😄 

Thanks
