### ISSUE TITLE
Show only coverage percentage

### ISSUE THREAD

**Issue by georgepaoli** [lucaslorentz/minicover#28]
Please, is possibile show only coverage percentage in a output report?

like this:
`$ dotnet minicover report --workdir ../ --threshold 90 --only-coverage-percentage`

output: 
`16.54% covered`

I intend to use it on Gitlab: https://gitlab.com/help/user/project/pipelines/settings#test-coverage-parsing

Thank you for this great job!

**Comment by lucaslorentz** [comment]
Hey @georgepaoli 
Thanks for the feedback.

I checked gitlab docs, and it supports specifying your own regex to find the coverage.
You can change the regex and then you don't need to change anything on minicover.

Use this regex: `All files.*\s(\d+.\d+%)`
http://rubular.com/r/e9Sq04plgm

But if you still want that feature on minicover, a PR is very welcome.

**Comment by georgepaoli** [comment]
Thank you very much @lucaslorentz !

> a PR is very welcome

Yes, I need to learn more your code.

Thanks for the invitation!

**Comment by grigorov** [comment]
Sorry, i fix regex: 

> All files.*\s(\d+.\d+.%)

http://www.rubular.com/r/QYtORG4yCm
