### ISSUE TITLE
Possible to exclude a file/directory from coverage?

### ISSUE THREAD

**Issue by abe545** [lucaslorentz/minicover#29]
Hi, first of all, this is great work, we definitely need this in .net land!

Is there a way to exclude a file or directory from the coverage metrics? I'm thinking specifically about tool generated code. We're writing grpc services, and want to exclude the codegen'd boilerplate that isn't useful to test.

**Comment by lucaslorentz** [comment]
Thanks.

Both parameters `--assemblies` and `--sources` have their counterparts `--exclude-assemblies` and `--exclude-sources`.

What you need is to exclude your GRPC sources, try adding:
`--exclude-sources src/SomeFolder/**/*.cs`

In case you need more options, here is the result of `minicover instrument --help`.

![instrumenthelp](https://user-images.githubusercontent.com/2268284/36614808-313c364e-18de-11e8-8896-159a610cc06e.PNG)

**Comment by abe545** [comment]
Whoops, should have tried to get help from the cli. Thanks for you help, though!
