### ISSUE TITLE
Provide Tests covering the code

### ISSUE THREAD

**Issue by bhugot** [lucaslorentz/minicover#33]
Would be nice to have the list of the tests who are covering the element of code.

**Comment by lucaslorentz** [comment]
That's a nice feature.
I'm not sure how we can do that though, maybe we can use callstack information:
At the beginning of every method we get a callstack snapshot, give it an id and save it's info to a file.
Then we correlate every hit inside the method to a callstack id.

**Comment by bhugot** [comment]
I started a branch on my fork for this feature. https://github.com/bhugot/minicover/tree/test_method_on_hit

**Comment by havocbcn** [comment]
Please, if this functionality (the list of tests who are covering the element of code) implies a great decrease of speed or huge amount of data, do something to disable it by parameters (or to enable it are optional), thanks!

**Comment by bhugot** [comment]
it s the case in my PR :)

**Comment by bhugot** [comment]
is it t
with the sample?

**Comment by bhugot** [comment]
I assume you are testing the Report it self, which report it is?

**Comment by havocbcn** [comment]
It's my project
the build.sh works well

The chat has removed some information, pasted again:

```
[xUnit.net 00:00:00.8485284]     ReportShould.ReportShould.RenderOneHundedPagesWithHeaderBodyBackgroundFooter [FAIL]
[xUnit.net 00:00:00.8497000]       System.TypeInitializationException : The type initializer for '<Module>' threw an exception.
[xUnit.net 00:00:00.8497650]       ---- System.FormatException : Input string was not in a correct format.

```

Now I have some time, I will try to view what happend

**Comment by bhugot** [comment]
it s when it s parsing the hit file can you post hit or delete hit and try again

**Comment by havocbcn** [comment]
I had a coverage-hits of 0 bytes and this cause the problem
Removed and tested again and works well.

My times:
[xUnit.net 00:00:00.6650546]   Starting:    SharpReportTest
[xUnit.net 00:00:40.1780215]   Finished:    SharpReportTest

coverage-hits.txt: 3755 bytes

Your times:
[xUnit.net 00:00:00.6260017]   Starting:    SharpReportTest
[xUnit.net 00:00:03.0008303]   Finished:    SharpReportTest
coverage-hits.txt: 3703 bytes

The opencovercoverage.xml is exactly the same.

**Comment by havocbcn** [comment]
Yes, was the hits file, I don't know why was not removed when the test started  (i use $MiniCover reset)

Sorry for the innecessary panic :D

great work

**Comment by bhugot** [comment]
Really faster then

**Comment by havocbcn** [comment]
Yes, can be used in develop-mode, much much better than the original code. I think that has to be fully tested (throw's scenarios, I don't have any), but in general, it has to work.

I'm uploading to sonarqube to watch if appear any difference...

(PD: the difference between coverage-hits file size is because my solution instrument the test itself),

**Comment by havocbcn** [comment]
Sonarqube, perfect, I'm looking forward to see it merged in the original code and deployed in nuget :)

**Comment by bhugot** [comment]
could you try the with tests version --with-hiting-tests to see the perf on your project. but I think at an improve when 2 hits come from same test method should be counted only as one hit

**Comment by havocbcn** [comment]
--with-hiting-tests: cancelled  when it takes more than 18 minutes

**Comment by bhugot** [comment]
ok thanks

**Comment by lucaslorentz** [comment]
@bhugot What if you cache the test method information using AsyncLocal or other similar, it should improve performance a lot.

It's very expensive to get test method for every instruction that is executed.

**Comment by bhugot** [comment]
yeah AsyncLocal do job quiet well. I also implemented an optimized way to get the method that goes twice faster than basic stackstrace

**Comment by bhugot** [comment]
@havocbcn if you have some times to retry --with-hiting-tests with my last version.

**Comment by havocbcn** [comment]
[xUnit.net 00:00:00.6282334]   Starting:    SharpReportTest
[xUnit.net 00:00:06.4508111]   Finished:    SharpReportTest

file size 874396 bytes

**Comment by bhugot** [comment]
So not bad at all with tests include
