### ISSUE TITLE
Exception when executing in Bitbucket Pipeline

### ISSUE THREAD

**Issue by JasonLearmouth** [lucaslorentz/minicover#4]
I get the following exception when running in BitBucket Pipelines container (Linux). The commands work on my local Windows machine.

> dotnet minicover instrument --workdir ../ --assemblies ../ConnectWiseWebHookGUI/**/bin/**/ConnectWiseWebHookGUI.dll --sources ../ConnectWiseWebHookGUI/**/*.cs --exclude-sources ../ConnectWiseWebHookGUI/**/obj/**/*.cs
> Specify --help for a list of available options and commands.
> Unhandled Exception: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument '../ConnectWiseWebHookGUI/Models/ConnectWiseConfig.cs'
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
>    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at MiniCover.Program.Main(String[] args)

**Comment by mrjavaguy** [comment]
I am seeing a lot of double forward slashes `//` is it possible that is throwing things off?

**Comment by JasonLearmouth** [comment]
That's a good point, but those extra forward slashes are not in my bitbucket-pipelines.yml file where the commands are defined.

`dotnet minicover instrument --workdir ../ --assemblies ../ConnectWiseWebHookGUI/**/bin/**/ConnectWiseWebHookGUI.dll --sources ../ConnectWiseWebHookGUI/**/*.cs --exclude-sources ../ConnectWiseWebHookGUI/**/obj/**/*.cs`

**Comment by mrjavaguy** [comment]
Oh something is eating the globs `**`. Can you try `dotnet minicover instrument --workdir ../ --assemblies '../ConnectWiseWebHookGUI/**/bin/**/ConnectWiseWebHookGUI.dll' --sources '../ConnectWiseWebHookGUI/**/*.cs' --exclude-sources '../ConnectWiseWebHookGUI/**/obj/**/*.cs'` 
I have seen that work in the past with yml files.

**Comment by lucaslorentz** [comment]
@JasonLearmouth

It seems to be related to shell commands/arguments parsing. As @mrjavaguy said, try adding quotes complex values like `../ConnectWiseWebHookGUI/**/bin/**/ConnectWiseWebHookGUI.dll`.

**Comment by lucaslorentz** [comment]
I believe the issue was outside minicover. Please, re-open the issue if something indicates otherwise.

**Comment by FastNinja** [comment]
Just to comment - had the same issue. Adding quotes helped. Also changing working dir to `./` also seemed to helped 
```
dotnet minicover instrument --workdir ./ --assemblies '../tests/**/bin/Debug/**/*.dll' --sources '../src/**/*.cs'
```
