### ISSUE TITLE
MsBuild integration to simplify instrumenting assemblies

### ISSUE THREAD

**Issue by lucaslorentz** [lucaslorentz/minicover#40]
I think it would be nice have integration with MsBuild to simplify assembly instrumenting.

Proposal:
- [ ] Split `coverage.json` and hits file per assembly, and place them in the assembly folder. So, `MyAssembly.dll` would have `MyAssembly.coverage.json` + `MyAssembly.coverage.hits`. (not sure about the names)
  - [ ] Generate files per assembly, at same folder the assembly is. I think the coverage file for each assembly would be similar to the `InstrumentedAssembly` model we have today.
  - [ ] Change reset command to search for all `*.coverage.hits` files inside folder and delete them.
  - [ ] Changes reporting commands to search on a folder for all `coverage.json` files and read them + hits
  - [ ] Change uninstrument command to find all `coverage.json`, restore assemblies backups and delete `coverage.json` + `hits file`
  - [ ] Change source files paths inside `coverage.json` to absolute paths. That would simplify minicover and would allow the assembly and coverage  file to be copied to any location without breaking it.
- [ ] Create MiniCover.MsBuild package with MsBuild targets that, right after compile, invoke the CLI tool to instrument the new assembly. I think that assembly + the coverage files will then be automatically copied to all projects that references it.

I think after those changes the experience would be:

1. Install `MiniCover.MsBuild` on projects you want to measure coverage.

2. Run build:
```
dotnet build
dotnet minicover reset SOLUTION_DIR
dotnet test ...
dotnet minicover report SOLUTION_DIR--threshold 90
dotnet minicover htmlreport SOLUTION_DIR--threshold 90 --source-base-path SOLUTION_DIR/src
dotnet minicover uninstrument SOLUTION_DIR
```

Maybe we don't need to uninstrument anymore because instrumentation would only happen in DEBUG compilation. So `dotnet publish -c Release` would not have instrumentation.

**Comment by lucaslorentz** [comment]
@bhugot 
Can you please take a look and let me know if you see any problems?

**Comment by day01** [comment]
> Generate files per assembly, at same folder the assembly is. I think the coverage file for each assembly would be similar to the InstrumentedAssembly model we have today.

Do you want to go into the direction? Now, parallel testing is unavailable with minicover.
@lucaslorentz

**Comment by lucaslorentz** [comment]
Now with .NET Core global tools I'm not sure if it worth to add msbuild integration.
I'm closing this one because I think we should prioritize bug fixes, then create .NET Core global tool.
