### ISSUE TITLE
Getting Ignoring modified file error on F# files

### ISSUE THREAD

**Issue by tomaxsas** [lucaslorentz/minicover#41]
Hi. Trying to Run coverage on F# project. Getting this error on most `.fs ` files:
```
Instrumenting assembly "Test.Api"
Ignoring modified file "C:\work\source_code\test-api\Test.Api\WebApiSuave.fs"
Ignoring modified file "C:\work\source_code\test-api\Test.Api\Persistence\DataAccess.fs"
Ignoring modified file "C:\work\source_code\test-api\Test.Api\Configurator.fs"
Ignoring modified file "C:\work\source_code\test-api\Test.Api\Common\DomainTypes.fs"
```
is this some sort of bug, or F# is not supported?

**Comment by lucaslorentz** [comment]
We use the file hash on PDB files to check if any source file was modified since the assembly was compiled.

Are you sure you have up to date assemblies? Maybe it is finding both Debug and Release assemblies, and one of them are outdated.

**Comment by tomaxsas** [comment]
After cleaning everything works, thanks!
