### ISSUE TITLE
Unhandled Exception: System.TypeInitializationException

### ISSUE THREAD

**Issue by aseduto** [lucaslorentz/minicover#50]
Publishing the code (_dotnet publish_), instrumenting it (_dotnet minicover instrument_) and then running it (_dotnet [path to the assembly]_) result in:
**Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileNotFoundException: Could not
 load file or assembly 'dotnet-minicover, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at .cctor()
   --- End of inner exception stack trace ---**
Looking at the dotnet core the issue maybe could be solved adding the dotnet-minicover.dll to the deps.json file.

**Comment by lucaslorentz** [comment]
Can you try modifying the deps.json and check if it works?

**Comment by aseduto** [comment]
Sure. I did it in this repository manually: _https://github.com/aseduto/sqlscript/tree/dev_ (dev).
I have tested it here: _https://ci.appveyor.com/project/aseduto/sqlscript/build/0.0.21_
This is where you can see the error: _https://ci.appveyor.com/project/aseduto/sqlscript/build/0.0.17_
This could be useful for collecting the coverage of integration tests.

**Comment by lucaslorentz** [comment]
Hey @aseduto , we added deps json patching on this PR: https://github.com/lucaslorentz/minicover/pull/56
Can you please try again with version 2.0.0-ci-20180318114828 ?

**Comment by aseduto** [comment]
Great!
Thank you it is working.
