### ISSUE TITLE
Nuget Error MiniCover.HitServices

### ISSUE THREAD

**Issue by thorgod** [lucaslorentz/minicover#52]
After a dotnet restore

Installing MiniCover 2.0.0-ci-20180316074459.
tools.csproj : error NU1101: Unable to find package MiniCover.HitServices. No packages exist with this id in source(s): nuget.org
`  <ItemGroup>
    <DotNetCliToolReference Include="MiniCover" Version="2.0.0-ci-20180314234126" />
  </ItemGroup>`

Was working a few days ago with 2.0.0-ci-20180314234126 (2 days ago) I will use this tell its stable again.

**Comment by thorgod** [comment]
I know its in dev, just wanted to give a heads up.  Maybe something with the CI

**Comment by bhugot** [comment]
Yeah I think we should only have one package

**Comment by lucaslorentz** [comment]
@thorgod 
This should be fixed on version MiniCover.2.0.0-ci-20180317075036.nupkg
Please, reopen this issue if you have any problems.
