### ISSUE TITLE
Wrong Test method with last Nunit3TestAdapter

### ISSUE THREAD

**Issue by bhugot** [lucaslorentz/minicover#57]
Nunit Team added the pdb file in there last release so the Test Method is always from there.
Maybe we should add some filter to eliminate the problem.
Or we ensure tests dll are flag some way even if we don't hit instrument them.

**Comment by lucaslorentz** [comment]
Now that we have that filtering, do we still need to check for PDB files?

**Comment by bhugot** [comment]
I don't check for all assembly used by those test framework assemblies so yes

**Comment by lucaslorentz** [comment]
Can we close this issue? PR is merged

**Comment by bhugot** [comment]
I will do another one to think about what I proposed as better fix
