### ISSUE TITLE
Is There an Elegent Way to configure Exclusions?

### ISSUE THREAD

**Issue by FastNinja** [lucaslorentz/minicover#64]
Hi there,
Great tool - now coverage is possible on Linux! 

The small annoying thing is to configure excluded files. Usually quote a lot of files/infrastrucutre boundaries should be excluded from unit tests - the list is quite large.
Is there a better way to specify exclusion?
Like OpenCover used special file for exclusion?

This is the what I have at the moment (long list..)

```
--exclude-sources '../src/**/Repositories/*.cs' --exclude-sources  '../src/**/Swagger'  --exclude-sources '../src/**/Data' --exclude-sources '../src/**/Startup.cs'  --exclude-sources '../src/**/Program.cs'  --exclude-sources <more exclusion here>
```

Thanks!

**Comment by AdrianCohea** [comment]
No promises, but I could try to put together a pull request for this. Seems simple enough to just add like ``--sources-exclusion-file```, and then File.ReadAllLines() on that and just stuff that into whatever collection ```--exclude-sources``` is already populating. I could really see that being useful in our project too.

BTW I just wanted to say that this project is very cool. As the advocate for .NET Core at my company, we're looking at this project with great interest.

**Comment by lucaslorentz** [comment]
@AdrianCohea , sounds like a good plan.
This is related: https://github.com/lucaslorentz/minicover/issues/68
Maybe it's better to add support for any parameter already, not only file exclusions.

**Comment by lucaslorentz** [comment]
Fixed on version [v3.0.0-alpha-1](https://github.com/lucaslorentz/minicover/releases/tag/v3.0.0-alpha-1)

[ExcludeFromCodeCoverage] attribute is now supported.
I think that's the most elegant way to configure exclusions.
It can be applied at assembly, class or method.

**Comment by hell-racer** [comment]
It doesn't work for me at assembly level :(

**Comment by duaneking** [comment]
@lucaslorentz With respect, this is a huge need and it actively gets in the way of usage and creates defects because minicover doesn't seem to understand that it should not be instrumenting tests by default.

I have a HUGE need for this feature and JSON is not a hard format as its natively supported by C#,  why are you so against it?
