### ISSUE TITLE
Could not load file or assembly 'dotnet-minicover'

### ISSUE THREAD

**Issue by roozbehid-ic** [lucaslorentz/minicover#65]
OS : Windows 10 
dotnet versin : 2.0

I do dotnet minicover instrument --workdir bin\Debug\netcoreapp2.0 --sources ..\..\..\*.cs on template generated project for asp.net core. and I get this error

    Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'dotnet-minicover, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
     at .cctor()
     --- End of inner exception stack trace ---

and there is already a dotnet-minicover.dll in output folder.
Although I could not find it in runtimeconfig.json and deps.json files.

------------------
I also ran the same thing under wsl in linux and got the same result. Meaning complaining about assembly dotnet-minicover not being found!

**Comment by lucaslorentz** [comment]
Please update minicover to latest version.
MiniCover 2.0.0-ci-20180321193925

**Comment by roozbehid-ic** [comment]
Thanks. it fixed the problem. So maybe update the readme file which most people would use.
