### ISSUE TITLE
Getting reports while app is running?

### ISSUE THREAD

**Issue by roozbehid-ic** [lucaslorentz/minicover#66]
Is there any way to dump coverage-hits file while application is running?
I am deploying instrumented asp.net core application inside a docker and I want to provide an API that while application is running somehow get the reports and also be able to reset counters.

Is there a way?Or suggestions how to achieve this?

**Comment by lucaslorentz** [comment]
I think now hits files are written before the application closes.
For example, every HTTP request in an ASPNET application will generate a hits file inside hits directory.

I think once in a while you can do a `docker exec CONTAINERID minicover report` in the same container to generate a report from the already created hits files, and another `docker exec CONTAINERID minicover reset` to reset.

**Comment by lucaslorentz** [comment]
No ideas for APIs though, maybe make an API that calls minicover executable and return result in HTTP response.
Or wait until minicover can be used as a library.
