### ISSUE TITLE
Add publish GitHub Release step to CI

### ISSUE THREAD

**Issue by abakumov-v** [lucaslorentz/minicover#71]
Hi!

Please add publish builded release to GitHub Release page (https://github.com/lucaslorentz/minicover/releases). If used AppVeyour for builds and publish to NuGet, I can help configure or you can see example: https://github.com/Valeriy1991/CQRSlight/blob/master/appveyor.master.yml

**Comment by lucaslorentz** [comment]
Hey @Valeriy1991 
Thanks for the suggestion and code reference.
We're planning proper releases on this PR: https://github.com/lucaslorentz/minicover/pull/61

Maybe you can add some suggestions and review it.

I'm planning to:
- Create tags/releases on Github for alphas, betas, rcs and final versions.
- Move CI packages to MyFeed.

I wasn't planning to push nuget packages to Github though.

**Comment by lucaslorentz** [comment]
Just FYI.
We didn't focus on a proper release process earlier because our main dependency didn't have final version.
They released it 7 days ago
https://www.nuget.org/packages/Mono.Cecil/

**Comment by lucaslorentz** [comment]
Fixed on version v3.0.0-alpha-1
