### ISSUE TITLE
Getting 0% coverage in black box tests

### ISSUE THREAD

**Issue by microsoftly** [lucaslorentz/minicover#75]
env:
* dotnet core 2
* linux

I have 2 sets of tests: unit and component. When running unit tests I get code coverage results as expected.

Unfortunately, when running component tests where I spin up our server from within the test, communicate with it via Http, and run assertions based on the request/responses I get 0% code coverage from the results of these tests.

Do you know why this may be and/or a way to get coverage when running this style test?

**Comment by bhugot** [comment]
are your server assemblies correctly instrumented?

**Comment by microsoftly** [comment]
How can I verify this? 

I'd imagine that
```dotnet minicover instrument --workdir ../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs```
would cover everything

**Comment by bhugot** [comment]
depend who launch your server ? try add all dll and all .cs to see.

**Comment by microsoftly** [comment]
I got the same results when adding all cs files and all dlls. The service is started from within the test project
``` dotnet minicover instrument --workdir ../ --assemblies ./**/bin/**/*.dll --sources ./**/*.cs ```

**Comment by lucaslorentz** [comment]
Are you setting the same --workdir on reports commands? That's necessary so minicover can find the hits file.

**Comment by pver** [comment]
Also make sure you use the '--no-build' option to run your test project (see script example in the readme) Because otherwise your instrumented version could get overridden with the uninstrumented version. 
Ran into that myself ;)

**Comment by microsoftly** [comment]
@pver You're a genius. That was indeed the issue.
