### ISSUE TITLE
OpenCover-flavored output does not match the actual OpenCover output

### ISSUE THREAD

**Issue by saxonww** [lucaslorentz/minicover#79]
I'm looking at MiniCover to replace OpenCover in a CI workflow. I am currently rewriting the OpenCover reports to Cobertura format for use with the Jenkins Cobertura plugin, using an [OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter) tool.

The MiniCover opencoverreport produces report output that doesn't really look like output produced by OpenCover, and the OpenCoverToCoberturaConverter tool can't process it. In particular, MiniCover produces a report which:

- has an `xsl-stylesheet` declaration instead of `xml`
- does not contain source elements (Class, File, Method, etc.) as children of parent elements (Classes, Files, Methods, etc.)
- does not have complexity or coverage metrics on Method elements
- does not have any Summary elements

I have not found a DTD for OpenCover, but there's an example report at https://github.com/sawilde/opencover/blob/master/samplexml/opencovertests.xml which I think they use for unit tests.

**Comment by lucaslorentz** [comment]
Was it completely addressed?
From the top of my head I know some items was addressed, but I don't remember anything about Summary Elements and other things.
It turns out those not addressed things are not necessary for some tools. Maybe it's not necessary for that converter either.

**Comment by saxonww** [comment]
I'm not sure yet. The newest couple of builds are throwing a new error "Common Language Runtime detected an invalid program" with some of my tests. It's only happening when instrumentation is active so I think it's a MiniCover thing; I am trying to track down which build introduced this and will open a separate issue.

**Comment by bhugot** [comment]
did you tried the last one?

**Comment by bhugot** [comment]
because it's something about instrumentation. I hope last version fixed them all but not sure

**Comment by saxonww** [comment]
I tried the most recent one 2.0.0-ci-20180328123752. The problem I'm seeing seems to have come in with 2.0.0-ci-20180325225037, which I am guessing was built from a297e00; when I run instrument with the build immediately prior to that I get an exception. When I use 2.0.0-ci-20180321193925 I can run tests without error; this one I think matches 2e3c8d0 which fixed the opencover schema.

The OpenCoverToCoberturaConverter util _works_ against this OpenCover report. I haven't run it through Jenkins to see what the report actually looks like, but there are no errors and the output file looks reasonable so I think this issue has indeed been solved.

**Comment by bhugot** [comment]
could you look at the code where you have those Common Language Runtime and share with me the code that is inpacted

**Comment by saxonww** [comment]
I opened #80 for this CLR issue since it's not really related to OpenCover reports
