### ISSUE TITLE
Sonarqube ignores coverage report when splitting jobs

### ISSUE THREAD

**Issue by pkaramol** [lucaslorentz/minicover#96]
Running unit tests in a job, producing coverage report and saving coverage artifacts:

    - git checkout origin/develop
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - cp -r /tools .
    - dotnet restore
    - dotnet build
    - cd tools
    - dotnet minicover instrument --workdir ../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs
    - dotnet minicover reset
    - cd ..
    - for project in test/**/*.csproj; do dotnet test --no-build $project; done
    - cd tools
    - dotnet minicover uninstrument --workdir ../
    - dotnet minicover opencoverreport --workdir ../ --threshold $COV_THRES
    - dotnet minicover report --workdir ../ --threshold $COV_THRES
    - cd ..
    artifacts:
      name: "coverage-report"
      paths:
        - opencovercoverage.xml
        - coverage-hits.txt
        - coverage.json
      expire_in: 1 hour

Running SQ in **another** stage (the above files __are__ available as an `ls` command shows):

    script:
      - mono /msbuild/SonarQube.Scanner.MSBuild.exe begin /d:sonar.login=$SONARQUBE_TOKEN /d:sonar.host.url=$SONAR_URL /v:$PROJECT_VERSION /k:$SONAR_PROJECT_KEY /d:sonar.cs.opencover.reportsPaths="opencovercoverage.xml".
      - dotnet restore
      - dotnet build
      - ls -al
      - mono /msbuild/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$SONARQUBE_TOKEN

Sonarqube reports `0.0%` coverage.

This is __NOT__ the case when combining the above jobs in a single one.

Why is that?

  [1]: https://github.com/lucaslorentz/minicover

**Comment by lucaslorentz** [comment]
Late response, but all I can think of is that the hits files are being between the 2 stages.

I hope you fixed the issue, or maybe switched to another coverage tool 😄
