### ISSUE TITLE
Out of memory (and time)

### ISSUE THREAD

**Issue by dbogatov** [lucaslorentz/minicover#97]
The tool is specifically demanding for large number of tests / hits.

I have a project (not yet open source) that has 357 tests so far for about 20 files of code.
These are cryptographic schemes and most tests just use different schemes with different parameters and perform couple thousand encryptions / decryptions.

The tool works, but it consumes 13 Gb of RAM and takes 15 minutes.
I noticed, it happens **after** instrumentation.
Just when I issue `report` command (regardless of report type).

My guess is that the way minicover reads its own artifacts is inefficient.
Maybe, it reads a big file large number of times?

Regardless, no reasonable CI will run test coverage consuming 13 Gb and 25 minutes for a medium sized project.
So I suggest we review the way report is generated.

I cannot share my whole project, but I think I can share `coverage.json` and `coverage-hits.txt` which happens to be a binary file of size 1 Gb.
Would that help?

*UPD:* in my `coverage.json` the last ID is 2048 and the number of lines 27221.

**Comment by dbogatov** [comment]
Even worse

![screen shot 2018-06-04 at 23 35 24](https://user-images.githubusercontent.com/5620695/40953916-fc9d1f22-684f-11e8-8787-328309ad0108.png)

**Comment by lucaslorentz** [comment]
Is it more lightweight if you also collect coverage from test source files? I mean something like `--sources src/**/*.cs --sources tests/**/*.cs`.

I guess the problem might be on the feature that detects which test hist each line. If that's the case, I have some ideas on how to improve it.

**Comment by dbogatov** [comment]
I will test that assumption now.
It is indeed a great feature that I can know which lines are hit by which tests, but if I could opt out for the sake of performance (like `--no-tests-per-line` flag), that would be awesome.

I have just aborted another coverage report generation because it took 71 Gb and whole night and still did not produce report.

BTW, could a part of the problem be that the generated binary file is 6 Gb and the tool reads it all into RAM? It would not even work for small droplets in CI...

**Comment by dbogatov** [comment]
You were right indeed!

Report generation is almost instantaneous if I include tests as sources.
Also, I have reduce number of iterations within tests and it got even faster.

Now artifacts are under 2 Mb.

The only caveat is that final percentage now includes tests and the number is lower than it should have been.
So if you could implement the `--no-tests-per-line` switch, it would be perfect.

**Comment by dbogatov** [comment]
@lucaslorentz any update on this?
For now my percentage includes test files and is therefore lower than it should be.

**Comment by lucaslorentz** [comment]
Fixed on version [v3.0.0-alpha-1](https://github.com/lucaslorentz/minicover/releases/tag/v3.0.0-alpha-1)

Option 1: 
Include test files using new tests parameter `--tests tests/**/*.cs`. They will be instrumented to recognize invoked methods, but will not be considered in code coverage.

Option 2:
Keep using `--sources src/**/*.cs --sources tests/**/*.cs` and add [ExcludeFromCodeCoverage] to test assembly, or classes or methods.
