### ISSUE TITLE
No executable found matching command "dotnet-minicover"

### ISSUE THREAD

**Issue by ableme** [lucaslorentz/minicover#99]
For .net core 2.1.301, cannot execute command - dotnet minicover

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MiniCover" Version="2.0.0-ci-20180517205544" />
  </ItemGroup>
</Project>
```

**Comment by lucaslorentz** [comment]
Hey @ableme 
Did you try with 
<DotNetCliToolReference Include="MiniCover" Version="2.0.0-ci-20180517205544" />
?

**Comment by ableme** [comment]
With `<DotNetCliToolReference Include="MiniCover" Version="2.0.0-ci-20180517205544" />`
it works. Actually, it is my bad that I added minicover with dotnet command `dotnet add package MiniCover --version 2.0.0-ci-20180517205544`  and did not notice that it was added as a package rather than cli tool

Thank you very much.
